services:
  # The Logic Engine
  core:
    image: markskinner92/iss300-simulator-core:v0.1.0
    build:
      context: ./services/core
    container_name: core
    depends_on:
      - modbus
    restart: unless-stopped
    extra_hosts:
      - "redis:host-gateway"
    env_file:
      - .env

  # Modbus bridge
  modbus:
    image: markskinner92/iss300-simulator-modbus:v0.1.0
    build:
      context: ./services/modbus
      dockerfile: Dockerfile
    container_name: modbus
    restart: unless-stopped
    extra_hosts:
      - "redis:host-gateway"
    devices:
      - "${MODBUS_PORT}:${MODBUS_PORT}"
    env_file:
      - .env
    environment:
      - DEBUG_MODE=0
    group_add:
      - dialout

  # The Socket.io <-> Redis Bridge
  gui-gateway:
    image: markskinner92/iss300-simulator-gui-gateway:v0.1.0
    build:
      context: ./services/gui
      dockerfile: Dockerfile.gateway
    container_name: gui-gateway
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "redis:host-gateway"
    ports:
      - "3000:3000" # for the socket.io server
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
      - DEBUG_MODE=0

  # The Vue.js Production Server (compiles the source in image build, and runs it without vite)
  gui-frontend-prod:
    profiles: ["prod"]
    image: markskinner92/iss300-simulator-gui-frontend-prod:v0.1.0
    build:
      context: ./services/gui/frontend
      dockerfile: Dockerfile.frontend.prod
    container_name: gui-frontend-prod
    restart: unless-stopped
    ports:
      - "5173:5173"

  # Manages external network connectivity
  network-controller:
    image: markskinner92/iss300-simulator-network-controller:v0.1.0
    build:
      context: ./services/network-controller
    container_name: network-controller
    restart: unless-stopped
    # Privileged is often needed to change hardware states (WiFi/Ethernet)
    privileged: true
    network_mode: "host" 
    volumes:
      # This allows the container to talk to the host's NetworkManager
      - /var/run/dbus:/var/run/dbus
      - /etc/NetworkManager/system-connections:/etc/NetworkManager/system-connections:rw
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://127.0.0.1:6379 # Since network_mode is 'host', use 127.0.0.1
      - SYSTEM_CONNECTIONS_DIR=/etc/NetworkManager/system-connections